global:
  scrape_interval:     5s
  external_labels:
    monitor: 'outline-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name:       'ss-server'
    static_configs:
      - targets: ['localhost:8080']
